spring:
  datasource:
      url: jdbc:mysql://localhost:3306/4c
      #jdbc????? ????jdbc:mysql://????????:??/????
      username: 4C
      #?????
      password: 19805601056Bkj
      #?????
      driver-class-name: com.mysql.cj.jdbc.Driver
      #??????

      #???MySQL????????????????????
    #??????

  ai:
    openai:
      api-key: sk-y0Z0z1lhHxwzhJB8awQXG2Z6QpyyiEQyDhUpAzfbcxg59mSv # 填写实际的API密钥
      base-url:  https://xiaoai.plus #路径

#???MySQL????????????????????
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:${file.upload-dir}/ # 确保后面有 `/`，以便指向文件夹

file:
  upload-dir: ./uploads  # 上传目录配置
